# Generated by Django 5.0.7 on 2024-07-27 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role_payment_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 10, 43, 22, 748309, tzinfo=datetime.timezone.utc), verbose_name='Дата платежа'),
        ),
    ]
